export const currencies = [
  { code: "AED", name: "UAE Dirham", flag: "ae" },
  { code: "AUD", name: "Australian Dollar", flag: "au" },
  { code: "BDT", name: "Bangladeshi Taka", flag: "bd" },
  { code: "BRL", name: "Brazilian Real", flag: "br" },
  { code: "CAD", name: "Canadian Dollar", flag: "ca" },
  { code: "CHF", name: "Swiss Franc", flag: "ch" },
  { code: "CNY", name: "Chinese Yuan", flag: "cn" },
  { code: "DKK", name: "Danish Krone", flag: "dk" },
  { code: "EGP", name: "Egyptian Pound", flag: "eg" },
  { code: "EUR", name: "Euro", flag: "eu" },
  { code: "GBP", name: "British Pound Sterling", flag: "gb" },
  { code: "HKD", name: "Hong Kong Dollar", flag: "hk" },
  { code: "IDR", name: "Indonesian Rupiah", flag: "id" },
  { code: "INR", name: "Indian Rupee", flag: "in" },
  { code: "JPY", name: "Japanese Yen", flag: "jp" },
  { code: "KRW", name: "South Korean Won", flag: "kr" },
  { code: "KWD", name: "Kuwaiti Dinar", flag: "kw" },
  { code: "MXN", name: "Mexican Peso", flag: "mx" },
  { code: "MYR", name: "Malaysian Ringgit", flag: "my" },
  { code: "NOK", name: "Norwegian Krone", flag: "no" },
  { code: "NZD", name: "New Zealand Dollar", flag: "nz" },
  { code: "PHP", name: "Philippine Peso", flag: "ph" },
  { code: "PLN", name: "Polish Zloty", flag: "pl" },
  { code: "RUB", name: "Russian Ruble", flag: "ru" },
  { code: "SAR", name: "Saudi Riyal", flag: "sa" },
  { code: "SEK", name: "Swedish Krona", flag: "se" },
  { code: "SGD", name: "Singapore Dollar", flag: "sg" },
  { code: "THB", name: "Thai Baht", flag: "th" },
  { code: "TRY", name: "Turkish Lira", flag: "tr" },
  { code: "TWD", name: "New Taiwan Dollar", flag: "tw" },
  { code: "UAH", name: "Ukrainian Hryvnia", flag: "ua" },
  { code: "USD", name: "United States Dollar", flag: "us" },
  { code: "VND", name: "Vietnamese Dong", flag: "vn" },
  { code: "ZAR", name: "South African Rand", flag: "za" },
];
